Fix performance issues with seeking while audio is playing
katspaugh/wavesurfer.js pull request #2045
Opened 2020-08-20 15:42 UTC by todoroff

When making calls to the `seekTo` method while the audio is playing, we were experiencing a issues with console errors and performance (to the point of the UI becoming completely unresponsive in the case of high-frequency seeking) because of unnecessary calls to `start` and `pause` inside that method.

Making the `seekTo` method `async` and awaiting the calls to `pause` and `start` inside solved the errors and the performance hit for low-frequency seeks (less than ~3 seeks per second) but wasn't good enough for higher-frequency seeking due to too much delay to resolve the promises.

We finally decided to remove those calls altogether, because they appear to be redundant. They were first introduced in #918, and supposedly solved an issue with backward seeking on `MediaElement`, which I wasn't able to replicate (tested with a 30 min long .ogg file).

2020-08-21 05:55 UTC, todoroff commented
> It should probably be removed, but did you run the javascript profiler on your code to confirm that the calls to play() and pause() are slow?
> 
> It's been 6 years so the original issue with mediaelement is probably fixed and we can remove the play/pause calls

I haven't run a profiler.

What happens is that if you ca play and pause too fast one after the other, you get errors `DOMException: The play() request was interrupted`. After several of those, the entire browser bogs down until you hit pause.

If you do make sure those calls run sequentially, meaning after each one is complete, there are no UI responsiveness issues but you can't seek as fast as when the audio is not playing, which simply doesn't feel nice.

2020-08-23 19:01 UTC, osheroff commented
i'd definitely check this against a bunch of browsers and html-audio vs media-element combos.  iOS/Safari tends towards "wildly different in behavior" vs firefox/chrome

2020-08-25 12:55 UTC, sundayz commented
BTW if you want high performance you should be using WebAudio instead of MediaElement.

I assume you want to allow users to seek by dragging the cursor with the mouse during playback? With WebAudio you have more fine control over audio buffers etc which is needed for something like that.

2020-08-26 18:58 UTC, realies commented
Works fine on Safari 13.1.2 (15609.3.5.1.3) over here.

2020-08-27 17:26 UTC, todoroff commented
@osheroff Works on Safari.
@sundayz We need MediaElement for our usecase.

2020-09-25 10:59 UTC, thijstriemstra requested changes
thanks @todoroff. I think we should give it a try; less is more. Can you add a changelog entry?

2020-09-25 15:19 UTC, thijstriemstra commented on CHANGES.md
> +- Fix performance issues with `seekTo` while audio is playing (#2045)
can you move this entry to a new section on top called 

```
Next (unreleased)
------------------
```

2020-09-25 15:30 UTC, thijstriemstra approved these changes

2020-09-25 15:31 UTC, merged