[setPlaybackRate] Webaudio backedn
katspaugh/wavesurfer.js pull request #2118
Opened 2020-11-28 20:45 UTC by marizuccara

webaudio backend: set playback rate modifying directly the playback property of the source node. Removed invocation to pause and play

### Breaking in the external API:
None

### Breaking changes in the internal API:
none

### Related Issues and other PRs:
https://github.com/katspaugh/wavesurfer.js/issues/2113

2020-11-30 04:02 UTC, sundayz approved these changes

2020-12-02 17:15 UTC, thijstriemstra requested changes
Two things:

- Coverage decreased (-15.9%) to 66.523% (???)
- tests are failing

2020-12-07 23:12 UTC, thijstriemstra requested changes
thanks! can you also add a changelog entry?

2020-12-12 19:59 UTC, thijstriemstra approved these changes

2020-12-12 20:01 UTC, merged