ensure webaudio is removed from ram/cpu usage
katspaugh/wavesurfer.js pull request #2164
Opened 2021-01-23 03:26 UTC by entonbiba

fixes #1940

2021-01-23 03:40 UTC, entonbiba commented
@katspaugh @thijstriemstra `backend = null` will happen as long as `backend` is available

``` javascript
if (this.backend) {
  this.backend.destroy();
  this.backend.buffer = null;
}
```

2021-01-23 08:02 UTC, sundayz commented
Your comment on #1940 says we should set this.backend to null but this commit sets this.backend.buffer to null, so which is it :)

Your research into the issue is great.  if we know loading new audio allows the memory to be garbage collected, we can follow that code path and see what it is doing that we are not doing in the destroy() function.

2021-01-23 12:06 UTC, marizuccara commented
Hi, also the audio buffer is already set to null in the `WebAudio` backend (which is the only backend that uses the `AudioBuffer`).

I hope that setting the backend to null will resolve all your problems! :)

2021-01-23 12:11 UTC, sundayz commented
Here is something interesting I found that may be a piece of the puzzle...

WebAudio createSource sets a reference of the buffer on the source.
https://github.com/katspaugh/wavesurfer.js/blob/658bd921be60a64192331ce8511bf1bce68cc4ec/src/webaudio.js#L580


WebAudio disconnects the source, but never sets it to null.
https://github.com/katspaugh/wavesurfer.js/blob/658bd921be60a64192331ce8511bf1bce68cc4ec/src/webaudio.js#L509

So if when we call destroy() a reference to the backend still exists, then a reference to the buffer will still also exist. Might be part of the problem. And could explain why calling load() again as entonbiba has shown frees the memory, because a new source is set and the old one is collected.

2021-01-23 13:24 UTC, marizuccara commented
I found this interesting response on stackoverflow:

2021-01-23 14:06 UTC, marizuccara commented
I found this interesting response on stackoverflow:
https://stackoverflow.com/questions/55207924/does-the-web-audio-api-clear-out-a-source-node-after-it-finishes-playing

On destroy we can call also stop() on the source node, if it's playing (in WebAudio). On `onendend` event, we can disconnect it,  sets to null the buffer, and then the node, as you suggest

2021-01-23 15:06 UTC, entonbiba commented
@sundayz lol yes `backend = null` is correct, updated

2021-01-24 17:53 UTC, thijstriemstra requested changes
thanks. can you also expand the existing test for `destroy` and add an assertion that `backend` is `null`. Also add a changelog entry please (with a reference to the ticket this pr is closing).

2021-01-24 19:00 UTC, thijstriemstra commented on CHANGES.md
> +- Fixed memory leak with `destroy()` in `WebAudio` backend (#1778)
this should be #1940

2021-01-24 19:01 UTC, entonbiba commented on CHANGES.md
> +- Fixed memory leak with `destroy()` in `WebAudio` backend (#1778)
hmm, updated to correct pr

2021-01-24 19:26 UTC, entonbiba commented
@thijstriemstra added null check,

@sundayz yes the observation about the `load()` is correct as its replacing backend with new. In the destroy case it would become null for this to work since even if we did .close or .disconnect it would still keep it as suspended taking up memory usage in webaudio.

2021-01-24 19:37 UTC, thijstriemstra commented
@entonbiba I meant more somewhere along these lines: https://github.com/katspaugh/wavesurfer.js/blob/entonbiba-patch-webaudio-usage-fix/spec/wavesurfer.spec.js#L351

2021-01-24 20:29 UTC, entonbiba commented
@thijstriemstra I'll add `expect(wavesurfer.backend).toBeNull();` after the `destroy();` like below:

``` javascript
it('destroy', function(done) {
        manualDestroy = true;

        wavesurfer.once('destroy', function() {
            TestHelpers.removeElement(element);
            done();
        });
        wavesurfer.destroy();

        expect(wavesurfer.backend).toBeNull();
    });
```

2021-01-24 20:43 UTC, thijstriemstra commented on src/wavesurfer.js
> +            if (this.backend !== null) {
this null check can be removed, it's already doing that on line 1734

2021-01-24 22:39 UTC, thijstriemstra approved these changes

2021-01-25 07:13 UTC, katspaugh approved these changes
Great work!

2021-01-25 12:30 UTC, merged

2021-01-25 19:59 UTC, sundayz commented
I haven't tried the new branch but in my project when I set backend = null, a little bit more memory gets collected but the 50MB arraybuffer still remains there.

2021-01-25 20:15 UTC, thijstriemstra commented
Feel free to re-open ticket closed by this pr: #1940

2021-01-26 00:06 UTC, entonbiba commented
@sundayz do you have the code you are using the create the instances ?
Just tried it again with `backend = null` and the results are working:

- create
- load
- backend = null
![image](https://user-images.githubusercontent.com/5193884/105781302-5e535f80-5f40-11eb-82fc-eadc07d19d3c.png)

2021-01-26 00:49 UTC, sundayz commented
The file is 2000 lines long and it uses Vue so we should test in a code pen :D I will try that tomorrow. I just have a feeling that if the issue was as simple as `backend = null` then it would have been fixed a long time ago.

If your PR fixes the leak for most people then it's still a very good thing. I will try to reproduce the issue without Vue later.

2021-01-26 01:16 UTC, entonbiba commented
@sundayz  if it's 2000 lines of vue then it's likely rendering a whole lot more than the audio file that's taking up memory.

The best test is to the library without any additional things. I just do `create` `load` `destroy (backend=null) pr` and repeat that multiple times with multiple loads at once to see the differences of usage.

ping me when the sample code is available I'll test it as well :)

2021-02-24 20:08 UTC, thijstriemstra commented
Unfortunately this PR introduced a new issue with timing issues around `backend = null`. In unit tests for a wavesurfer related project I started seeing this error:

```
  TypeError: Cannot read property 'getCurrentTime' of null
      at WaveSurfer.getCurrentTime (node_modules/wavesurfer.js/dist/wavesurfer.js:4199:27)
      at d.value (dist/commons.js:8:71353)
      at d.value (dist/commons.js:8:69669)
      at d.value (dist/commons.js:8:74618)
      at node_modules/wavesurfer.js/dist/wavesurfer.js:3214:12
      at <Jasmine>
      at WaveSurfer.fireEvent (node_modules/wavesurfer.js/dist/wavesurfer.js:3213:28)
      at node_modules/wavesurfer.js/dist/wavesurfer.js:4133:16
      at node_modules/wavesurfer.js/dist/wavesurfer.js:3214:12
      at <Jasmine>
```

Commenting out the `backend = null` change from this PR makes the test pass again.

Basically any code in wavesurfer that relies on the `backend` property, e.g. `wavesurfer.getCurrentTime()` will now break if `destroy()` is called. This is not necessarily a bad thing, the instance was destroyed afterall, but should wavesurfer fix this (e.g. add a backend !== null check everywhere) or is it up to the user to check for an proper, existing `wavesurfer.backend` property?

2021-02-24 20:41 UTC, thijstriemstra commented
> but should wavesurfer fix this (e.g. add a backend !== null check everywhere) or is it up to the user to check for an proper, existing wavesurfer.backend property?

Turns out it was an issue with my tests and this change brought it to light, so no worries, sorry for the noise.

2021-03-01 23:36 UTC, entonbiba commented
sounds good