Test release
katspaugh/wavesurfer.js pull request #2241
Opened 2021-04-05 17:52 UTC by katspaugh

@thijstriemstra thanks for the docs link, it worked nicely 👍 

I've also reorganised the steps a bit, so that each command have a separate title.

Here's the build that published release 4.4.0: https://github.com/katspaugh/wavesurfer.js/runs/2271665459?check_suite_focus=true

Closes ##2231.

2021-04-05 18:02 UTC, thijstriemstra requested changes
Nice! The release name should be corrected though, see https://github.com/katspaugh/wavesurfer.js/releases/tag/4.4.0

2021-04-05 18:02 UTC, thijstriemstra commented on .github/workflows/publish.yml
> +          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
can you add some spaces around this var (e.g. see line 48)

2021-04-05 21:00 UTC, katspaugh commented
Fixed the name format ✅

2021-04-05 21:17 UTC, thijstriemstra commented on .github/workflows/publish.yml
> +      - name: Tag
CMake it more descriptive, e.g. `Create Git tag`

2021-04-05 21:27 UTC, thijstriemstra commented
Maybe this is a bonus-points kind of thing, but for some reason the author name is `github-actions`, would be nice if it's the person tagging or creating the release. Renaming `github-actions` to something more general should be fine as well, e.g. `wavesurfer.js`

![Screenshot from 2021-04-05 23-25-00](https://user-images.githubusercontent.com/305679/113629235-6decd400-9666-11eb-8301-606af1d1fd51.png)

2021-04-05 21:30 UTC, thijstriemstra commented on .github/workflows/publish.yml
> +            git tag $(cat version.txt)
adding some echo statements describing the flow you added would help as well

2021-04-06 09:21 UTC, thijstriemstra approved these changes
thanks!

2021-04-06 12:07 UTC, merged