Vertical orientation regions
katspaugh/wavesurfer.js pull request #2242
Opened 2021-04-05 18:32 UTC by valrus

### Short description of changes:
This PR adds support for vertically-oriented waveforms to the regions plugin. It's a follow up to the original vertical waveform PR #2195.

### API breakages:
None AFAIK.

### Todos/Notes:
Other plugins still need vertical track support.

### Related Issues and other PRs:
PR #2195, issue #634.

2021-04-05 21:33 UTC, thijstriemstra requested changes
lot's of changes going on here, hard to review as I don't use/focus on regions plugin.

2021-04-05 21:33 UTC, thijstriemstra commented on src/plugin/regions/region.js
> +            this.wrapper.removeChild(this.element.proxiedElement);
this should be `domElement` afaik

2021-04-06 07:33 UTC, katspaugh commented
Thanks for the cool PR @valrus!

Do you have it deployed anywhere so that we can play around with the vertical waveform?

2021-04-10 18:54 UTC, valrus commented
> Thanks for the cool PR @valrus!
> 
> Do you have it deployed anywhere so that we can play around with the vertical waveform?

Hey - sorry, I don't. I'm using it in a personal project but it's not ready to be more publicly available yet. When I have the time maybe I can throw up a basic demo that doesn't depend on a server like the aforementioned project does.

2021-04-12 05:30 UTC, valrus commented
@katspaugh OK, I tossed up a quick demo for you! It's really just the existing `regions` example with `vertical: true` and some CSS tweaks also used in the current `vertical` example. Here it is: https://ian.mccowan.space/wavesurfer-vertical-demo/

2021-04-12 07:23 UTC, katspaugh commented
Works great, thank you!

2021-04-12 07:24 UTC, katspaugh approved these changes

2021-04-13 19:39 UTC, thijstriemstra approved these changes
thanks!

2021-04-13 19:40 UTC, merged