markers plugin: added support for custom marker images
katspaugh/wavesurfer.js pull request #2269
Opened 2021-05-13 13:50 UTC by bknower

# Hey, thank you for contributing to wavesurfer.js!

To review/merge open PRs it is very helpful to know as much as possible about the changes which are being introduced. Reviewing PRs is very time consuming, please be patient, it can take some time to do properly.

**Title:** Please make sure the name of your PR is as descriptive as possible (Describe the feature that is introduced or the bug that is being fixed).

## Please make sure you provide the information below:

### Short description of changes:
Markers can now be provided with an image to display instead of the default pointer image when being added.

### Breaking in the external API:

### Breaking changes in the internal API:

### Todos/Notes:

### Related Issues and other PRs:

2021-05-13 15:02 UTC, thijstriemstra commented
good idea. what if someone wants to add videos, we'd have to add another parameter to that method, I'd prefer a different approach that would make it easy to support various types (eg audio/video/img).

2021-05-13 15:20 UTC, bknower commented
> good idea. what if someone wants to add videos, we'd have to add another parameter to that method, I'd prefer a different approach that would make it easy to support various types (eg audio/video/img).

Does it make sense to display anything other than an image as a marker? This is just for the markers like this 
![image](https://user-images.githubusercontent.com/28788241/118146974-1ff18b80-b3dd-11eb-9e5b-979581eed74d.png)

2021-05-17 15:23 UTC, thijstriemstra requested changes
> Does it make sense to display anything other than an image as a marker?

Yeah, a canvas element. But also an html element like a button or checkbox. Can you make it more generic? Also, can you add this new feature to the markers example?

2021-05-25 11:42 UTC, thijstriemstra requested changes
thanks. can you also document the new option here: https://github.com/katspaugh/wavesurfer.js/blob/554ba967c8da3e271fab911c4ca8b0eaa4260806/src/plugin/markers/index.js#L3

And add a changelog entry?

2021-05-25 16:20 UTC, osheroff commented
needs documentation.  Interface is highly flexible but seems ripe for shooting yourself in the foot by re-using the same HTMLElement; I could see the argument for detecting that case?  I was going to say "just use `cloneNode`" but maybe that hampers some use cases.   Dunno.

@thijstriemstra is there an example of a plugin accepting an HTMLElement we could follow?

2021-05-25 18:31 UTC, thijstriemstra commented
> is there an example of a plugin accepting an HTMLElement we could follow?

Not that I know of. I think this PR is good enough for a first implementation.

2021-05-25 19:37 UTC, thijstriemstra commented on CHANGES.md
> +- Markers plugin: add the ability to use custom HTML elements in place of the default marker icon by passing the new `markerElement` parameter to the marker constructor (#2269)
move this changelog entry to a new section called `x.x.x (unreleased)`

2021-05-27 11:17 UTC, thijstriemstra approved these changes
thanks.

2021-05-27 11:23 UTC, merged