Fixes #2279 and #1473
katspaugh/wavesurfer.js pull request #2311
Opened 2021-06-22 11:53 UTC by vespakoen

# Hey, thank you for contributing to wavesurfer.js!

To review/merge open PRs it is very helpful to know as much as possible about the changes which are being introduced. Reviewing PRs is very time consuming, please be patient, it can take some time to do properly.

**Title:** Please make sure the name of your PR is as descriptive as possible (Describe the feature that is introduced or the bug that is being fixed).

## Please make sure you provide the information below:

Fixes

`Failed to execute 'stop' on 'AudioScheduledSourceNode'`

and

`Cannot read property 'decodeArrayBuffer' of null`

(both timing / state issues)

### Short description of changes:

Adds the necessary checks to stop errors from happening.

### Breaking in the external API:

none

### Breaking changes in the internal API:

none

### Todos/Notes:

none

### Related Issues and other PRs:

#2279
#1473

2021-06-22 21:34 UTC, thijstriemstra requested changes
thanks! changes make sense. I preferred not to add a isDestroyed check everywhere but for this method I certainly don't mind.

can you also add a changelog entry? a new section with `x.x.x (unreleased)` is probably needed.

2021-06-22 21:34 UTC, thijstriemstra commented on src/webaudio.js
> +            // no-op, see https://github.com/katspaugh/wavesurfer.js/issues/1473
can you add a little more info so you only have to visit the ticket if you need all details

2021-06-22 21:43 UTC, thijstriemstra commented
Also; bonus points for adding a unit test that would fail without this change.

2021-06-30 17:09 UTC, vespakoen commented
I added the items to the changelog and a (hopefully) better comment.

I tried adding tests for these but it's pretty hard, since I don't know how I'd verify that an error threw.

I guess the test case would be something like:

```

    /** @test {WaveSurfer#destroy} */
    it('destroy while loading', function(done) {
        manualDestroy = true;

        wavesurfer.once('destroy', function() {
            TestHelpers.removeElement(element);
            done();
        });
        wavesurfer.load(TestHelpers.EXAMPLE_FILE_PATH);
        wavesurfer.destroy();

        // EXPECT NO THROWN ERRORS SOMEHOW?
    });
```

For the other issue it seems to happen when quickly starting / stopping a sound, perhaps something like:

```
    it('can quickly toggle', function() {
        wavesurfer.load(TestHelpers.EXAMPLE_FILE_PATH);
        wavesurfer.once('ready', () => {
            wavesurfer.play();
            wavesurfer.pause();
            wavesurfer.play();
            wavesurfer.pause();
            wavesurfer.play();
            wavesurfer.pause();
        });
    });
```

But it probably won't work all the time and is not elegant.

Basically, these are edge cases that happen in a rare situation that is hard to re-create in a test.

2021-07-03 16:04 UTC, thijstriemstra approved these changes
thanks!

2021-07-03 16:08 UTC, merged

2021-07-06 14:36 UTC, vespakoen commented
Thank you too!

@thijstriemstra Would it be possible to do a minor release for this change? I'd like to include it in an update to one of my projects tomorrow.

If not, that's also fine ;)