fixed bars sizing using max peak value in range
katspaugh/wavesurfer.js pull request #2428
Opened 2022-01-09 21:32 UTC by lorenzos

This changes the way drawer renders bars. Prior to this, the height of each bar was [calculated only on the single peak at the start of bar, in `drawer.multicanvas.js:311`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L311). This made the bars render almost randomly, especially at smaller widths, since highest peaks were very easily ignored, if not falling exactly where a bar started.

Here's an animated example of **before**, as you can see the original waveform is translated poorly, and then when resizing, bars jump around for no good reason:

![Bars size before](https://user-images.githubusercontent.com/245615/148701271-c5f8372e-220e-4c60-8654-3eb4c93923a3.gif)

Now instead, the height is [calculated on the whole range of peaks that each bar falls into](https://github.com/lorenzos/wavesurfer.js/commit/243a595a5c5684c44b06619d1aed4fe38fa93429#diff-9e1d85325663a8f99b981eac351eef64b1ed40011d998b4d502b6b6ac4115609R311). I used the [maximum peak value](https://github.com/lorenzos/wavesurfer.js/commit/243a595a5c5684c44b06619d1aed4fe38fa93429#diff-9e1d85325663a8f99b981eac351eef64b1ed40011d998b4d502b6b6ac4115609R315); average works too, but it would require normalization to make sure the taller bar is at maximum height.

Here's the same animated example **after**, the translation is better and bars re-sampling is definitely more consistent:

![Bars size after](https://user-images.githubusercontent.com/245615/148701169-d6299965-e38e-48fd-b6b8-b9cd227498e5.gif)

---

### Addendum

While fixing this, I noticed another issue when choosing the peak index to use for heights calculation. There is a [`peakIndexScale` to "skip every other value if there are negatives"](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L292) in the peaks array. It made sense, but was used incorrectly [in the actual formula](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L312), before the rounding (floor) instead of [after](https://github.com/lorenzos/wavesurfer.js/commit/243a595a5c5684c44b06619d1aed4fe38fa93429#diff-9e1d85325663a8f99b981eac351eef64b1ed40011d998b4d502b6b6ac4115609R312).

This made it possible to actually choose odd indexes, and therefore negative peak values. I guess this went unnoticed since the bar is mirrored anyway. Here's a comparison of chosen peaks before and after, note how the fix "snaps" to even indexes only:

![Peak indexes before](https://user-images.githubusercontent.com/245615/148701638-a9187954-a056-402a-bede-40afdbb12a8f.png) ![Peak indexes after](https://user-images.githubusercontent.com/245615/148701632-24db4369-5e9a-4b5f-b366-2cc5f5450fc5.png)

I also fixed this.

2022-01-12 11:46 UTC, thijstriemstra requested changes
thanks @lorenzos 

could you add as much comments in that piece of code as possible? It's hard to understand without any.

Also, please add a changelog entry.

2022-01-12 19:40 UTC, lorenzos commented
Done!

2022-01-12 21:11 UTC, thijstriemstra commented on src/drawer.multicanvas.js
> +
can you remove this empty line, and rename `let i` to something more meaningful?

2022-01-12 21:12 UTC, thijstriemstra commented on src/drawer.multicanvas.js
> +                    // calculate the height this bar according to highest peak found
`of` and `the` are missing in this comment

2022-01-13 14:17 UTC, thijstriemstra approved these changes

2022-01-13 14:17 UTC, merged