fixed bars rendering for peaks array starting with a negative value
katspaugh/wavesurfer.js pull request #2446
Opened 2022-02-10 20:19 UTC by lorenzos

Fixes #2439, an "unmasked" regression introduced with #2428. That regression broke bars rendering in the case a given pre-computed array of peaks alternates negative/positive values, instead of alternating positive/negative values (as wavesurfer itself generates).

2022-02-10 23:41 UTC, dtcooper requested changes
👏👍🖖

2022-02-12 13:12 UTC, thijstriemstra reviewed
thanks @lorenzos can you also add a comment for this line, explaining why abs is needed?

2022-02-12 21:32 UTC, thijstriemstra commented on CHANGES.md
> +
the issue nr is enough, the pr nr is not needed here

2022-02-13 00:13 UTC, thijstriemstra approved these changes

2022-02-13 00:17 UTC, merged