regions plugin: restore support for one drag selection for all channels
katspaugh/wavesurfer.js pull request #2551
Opened 2022-07-11 09:57 UTC by muhammad-sayed-mahdy

### Short description of changes:
add `splitDragSelection` (default false) in `splitChannelsOptions` and check on it when splitting the drag selection
### Todos/Notes:
maybe update annotation example to include this

### Related Issues and other PRs:
fixes #2529
refs #2380

2022-07-29 20:49 UTC, thijstriemstra commented on src/wavesurfer.js
> + * @property {boolean} splitDragSelection=false determines if drag selection in regions plugin works separately on each channel or only one selection for all channels
can you keep this sentence on multiple lines of <= 80 chars

2022-07-29 20:49 UTC, thijstriemstra requested changes
thanks @muhammad-sayed-mahdy 

could you give this a try @4ntke?

2022-07-30 13:48 UTC, thijstriemstra commented
thanks @muhammad-sayed-mahdy can you also add a changelog entry.

2022-07-30 14:15 UTC, muhammad-sayed-mahdy commented
@thijstriemstra should it go under version 6.3.0 (unreleased) ?

2022-07-30 14:31 UTC, thijstriemstra commented
@muhammad-sayed-mahdy sounds good

2022-07-30 20:22 UTC, thijstriemstra approved these changes
thanks.

2022-07-30 20:27 UTC, merged