Improved delta calculation (resize end)
katspaugh/wavesurfer.js pull request #2641
Opened 2023-01-09 18:50 UTC by BQTH

### Short description of changes:
With the use case that I use this library for, users need to be able to resize the regions. When a region was resized and afterward set back to the min length (f.e. 3.1 sec or in HMSM, which is how we show it, 00:00:03:10) it would stay at 3.12sec (00:00:03:12) or 3.14sec (00:00:03:14) or something, but never go back down all the way to 3.1 (00:00:03:10). With these changes, the length of the region can be set back to 3.10 exactly

2023-01-11 14:30 UTC, thijstriemstra commented on src/plugin/regions/region.js
> +
no need for this newline

2023-01-11 14:31 UTC, thijstriemstra commented on src/plugin/regions/region.js
> +             if (!delta) delta = time - startTime;
put if statement on multiple lines

2023-01-11 14:31 UTC, thijstriemstra commented on src/plugin/regions/region.js
> +
no need for this newline

2023-01-11 14:31 UTC, thijstriemstra requested changes
thanks, see inline comments. can you also add a changelog entry?

2023-01-12 08:52 UTC, BQTH commented
> thanks, see inline comments. can you also add a changelog entry?

Good morning, i've made the requested changes and added an entry to the changelog. This is my first time collaborating on a repo like this, hopefully i did it correctly. All feedback is welcome!

2023-01-12 14:43 UTC, thijstriemstra requested changes

2023-01-12 14:43 UTC, thijstriemstra commented on CHANGES.md
> +6.4.1 (12.01.2023)
you can use 6.5.0 (unreleased) instead

2023-01-13 12:39 UTC, thijstriemstra commented on CHANGES.md
> +6.5.0 (unreleased) (12.01.2023)
and remove the date ;)

2023-01-15 17:07 UTC, BQTH commented on CHANGES.md
> +6.5.0 (unreleased) (12.01.2023)
Done!

2023-01-25 10:20 UTC, thijstriemstra approved these changes
thanks!

2023-01-26 13:39 UTC, merged