Feat: `record-progress` event and `getDuration` method
katspaugh/wavesurfer.js pull request #3472
Opened 2024-01-08 03:19 UTC by aantusahaa

## Short description
Introduces a new event `record-progress` and a new method `getDuration`.
Resolves #3431 

## Implementation details

### `record-progress` event
Internal implementation keeps track of the time with `Clock` class. The clock will emit `tick` with `requestAnimationFrame`. It is heavily inspired by the already existing `Timer` class. Only difference is it keeps track of the time along with ticking. 

The clock will start when the media recording has begun. It will pause/resume accordingly as well. The clock will not reset until the next `record-start` event fires. 

### `getDuration` method
Always returns the `currentTime` from the `Clock`. Since the clock won't reset until the next start event, the consumer will be able to get the duration even after the recording ends.

## How to test it
There is a progress timer added in the `record.js` example.

## Screenshots

## Checklist
* [ ] This PR is covered by e2e tests
* [x] It introduces no breaking API changes

2024-01-08 07:45 UTC, katspaugh requested changes

2024-01-08 07:45 UTC, katspaugh commented on src/plugins/record.ts
> +  protected subscriptions: Array<() => void> = []
The BasePlugin already has this defined, so you don't have to.

2024-01-08 07:45 UTC, katspaugh commented on src/plugins/record.ts
> +    this.subscriptions.forEach((unsubscribe) => unsubscribe())
This can be replaced by `super.destroy()` (the BasePlugin unsubscribes from all events).

2024-01-08 07:45 UTC, katspaugh commented on src/clock.ts
> +      requestAnimationFrame(this.updateTime.bind(this))
We don't really have to update the time on each tick. You could just return `performance.now() - startTime` from `getCurrentTime`. On pause, you could save the intermediate duration into a variable. This is both much more accurate and efficient.

Check out thow time is tracked in this class: https://github.com/katspaugh/wavesurfer.js/blob/main/src/webaudio.ts#L148-L150

With this in mind, we could get away with just the Timer class + tracking the recording duration in the Record plugin itself, w/o creating a new Clock class.

2024-01-08 07:45 UTC, katspaugh commented
Thanks for the PR! 🙏 Made a couple comments.

2024-01-09 03:57 UTC, aantusahaa commented
Thanks for the pointer @katspaugh! Made some changes.

2024-01-09 06:36 UTC, katspaugh approved these changes
Nice, thank you, looks good to me!

2024-01-09 20:06 UTC, merged